version: '3.3'
services:
  matrix_app:
    container_name: matrix_app_container
    build:
      context: .
      args:
        - http_proxy=https://username:password@proxy-hostname:port/
        - https_proxy=https://username:password@proxy-hostname:port/
    ports:
      - '3000:3000'
    #volumes: For hot reload vue cli need to be locally installed
      #- .:/app